# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Adi Prasetyo, AP programming
subtitle: 'software engineer'
description: 'professional duck-typer developer'
keywords: 'adi prasetyo, adi p'
author: Adi Prasetyo
language: en,id
timezone: 'Asia/Jakarta'


# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://enter-rebel.github.io
permalink: :lang/:title/:year/
permalink_defaults:
  lang: en
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :lang/:title.md
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 18
  order_by: -date

feed:
  type: atom
  path: atom.xml
  limit: 40
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
# Category & Tag
default_category: writing
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
browsersync:
  logLevel: "warn"
  ghostMode:
    scroll: true
  instanceName: "uniqueString"
search:
  path: search.xml
  field: post
githubEmojis:
  enable: true
  className: github-emoji
  inject: true
  styles:
  customEmojis:
music:
  enable: false
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-matery
theme_config:
  googleAnalytics:
    enable: true
    id: G-TVF38M06ZZ #  unchecked
  profile:
    avatar: /res/ava_dark.png
  myProjects:
    data:
      caraka:
        icon: fas fa-database
        iconBackground: 'linear-gradient(to bottom right, #F06292 0%, #EF5350 100%)'
        url: https://github.com/brutalcrozt
        desc: medical check-up web app, sorry the project is private you can't
          see it
  mySkills:
    data:
      PHP:
        background: 'linear-gradient(to right, #1b5ee0 0%, #0a47bd 100%)'
        percent: 80%
      Java:
        background: 'linear-gradient(to right, #FF0066 0%, #FF00CC 100%)'
        percent: 25%
      JavaScript:
        background: 'linear-gradient(to right, #073bc2 70%,  100%)'
        percent: 0%
      # HTML5:
      #   background: 'linear-gradient(to right, #2196F3 0%, #42A5F5 100%)'
      #   percent: 100%
      SASS:
        background: 'linear-gradient(to right, #151118 70%, #80DEEA 100%)'
        percent: 4%
      CoffeeScript:
        background: 'linear-gradient(to right, #1714bb 70%, #0502a8 100%)'
        percent: 20%
      MySQL:
        background: 'linear-gradient(to right, #e24a6a 0%, #c2072e 100%)'
        percent: 80%
covers:
  enable: false
  title: 'please dont cp here'
  base_dir: '.covers'
  manifestFileName: 'enter-covers.json'
  include:
    - keywords
  tagsUrl: tag
  categoriesUrl: category
  compress: true
  source:
    categories:
        data: _data/categories.yml
        images: _covers/categories
    tags:
        data: _data/tags.yml
        images: _covers/tags
  templates:
    page:
      path: themes/theme1/layout/microbrowser-template/page.html
      images:
        logo: themes/theme1/source/assets/favicon/favicon-194x194.png
        background: themes/theme1/layout/microbrowser-template/bg.svg
      dimensions:
        width: 964
        height: 504
      post:
        path: themes/theme1/layout/microbrowser-template/post.html
        images:
          logo: themes/theme1/source/assets/favicon/favicon-194x194.png
          background: themes/theme1/layout/microbrowser-template/bg.svg
        dimensions:
          width: 964
          height: 504
      category:
        path: themes/theme1/layout/microbrowser-template/category.html
        images:
          logo: themes/theme1/source/assets/favicon/favicon-194x194.png
          background: themes/theme1/layout/microbrowser-template/bg.svg
        dimensions:
          width: 964
          height: 504
      tag:
        path: themes/theme1/layout/microbrowser-template/tag.html
        images:
          logo: themes/theme1/source/assets/favicon/favicon-194x194.png
          background: themes/theme1/layout/microbrowser-template/bg.svg
        dimensions:
          width: 964
          height: 504
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
